### ISSUE TITLE
Getting OOM while reading large file on Lollipop devices

### ISSUE THREAD

**Issue by gagan20** [sromku/android-simple-storage#12]
I tried to read and encrypt video file (though I used my own encryption algorithm), I got OOM exception. 

protected byte[] readFile(final FileInputStream stream) {
//...
}

Can you please help in that?

**Comment by MickDawdy** [comment]
I did a Google search for "OOM Exception". It is Out Of Memory Exception. Here are the first two responses ...

http://www.javacoffeebreak.com/faq/faq0027.html

http://stackoverflow.com/questions/19720956/get-oom-exception-when-sending-message-with-a-high-speed-with-netty

Mick

**Comment by gagan20** [comment]
I know what OOM exception is, I am just informing you that when I tried to read video file (around 20MB using device having only 512MB RAM and running Android 5.1.1), you code gave me OOM exception. You can check and fix the issue in your code.
