### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by StephaneBg** [sromku/android-simple-storage#5]
Please made this awesome library available on Maven Central.

**Comment by Laeyoung** [comment]
+1

**Comment by nsbrno** [comment]
How create a folder in root of internal storage

**Comment by jitpack** [comment]
Btw, you can get it as a dependency already now from https://jitpack.io/#sromku/android-simple-storage/1.0.0 
The syntax in Gradle would be:

    dependencies {
        compile 'com.github.sromku:android-simple-storage:1.0.0@aar'
    }

**Comment by mingfai** [comment]
+1

**Comment by MaximKorobov** [comment]
#8 patch adds to Maven local repository. What about Maven Central or jCentral?

**Comment by theManikJindal** [comment]
@jitpack  +1 Wasted 3+ hours to try and get Android Studio to work. But it did not work. Yours on the other hand was absolute magic.

**Comment by jendakol** [comment]
+1
